# Generated by Django 6.0.5 on 2026-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='credit_score',
            field=models.IntegerField(default=750),
        ),
    ]
