# Generated by Django 6.0.5 on 2026-05-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_loan_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='expiry_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='upi_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
