# Generated by Django 6.0.5 on 2026-05-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_account_card_number_account_cvv_account_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
